import Header from "../../components/header/header";
import Footer from "../../pages/Main/sections/footer/footer";
import React from "react";

//Styles
import classes from "./privacyPolicy.module.scss";

const PrivacyPolicy = () => {
  return (
    <section className={classes.wrapper}>
      <Header />
      <div className={classes.content}>
        <h1>SolidFish's Privacy Policy</h1>
        <p>
          Last updated: August 28, 2020
          <br />
          <br />
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
          <br />
          By using the Service, You agree to the collection and use of
          information in accordance with this Privacy Policy.
          <br />
          <b>Interpretation and Definitions</b>
          Interpretation
          <br />
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions.
          <br />
          The following definitions shall have the same meaning regardless of
          whether they appear in singular or in plural.
          <br />
          <b>Definitions</b>
          For the purposes of this Privacy Policy:
          <b>You</b>
          <br />
          means the individual accessing or using the Service, or the company,
          or other legal entity on behalf of which such individual is accessing
          or using the Service, as applicable.
          <br />
          <br />
          <b>Company</b>
          <br />
          (referred to as either "the Company", "We", "Us" or "Our" in this
          Agreement) refers to Solid.Fish Limited, 71-75 Shelton Street, London,
          Greater London, WC2H 9JQ, United Kingdom.
          <br />
          <br />
          <b>Affiliate</b>
          <br />
          means an entity that controls, is controlled by or is under common
          control with a party, where "control" means ownership of 50% or more
          of the shares, equity interest or other securities entitled to vote
          for election of directors or other managing authority.
          <br />
          <br />
          <b>Account</b>
          <br />
          means a unique account created for You to access our Service or parts
          of our Service.
          <br />
          <br />
          <b>Website</b>
          <br />
          refers to SolidFish, accessible from https://solid.fish
          <br />
          <br />
          <b>Service</b>
          <br />
          refers to the Website.
          <br />
          <br />
          <b>Country</b>
          <br />
          refers to: United Kingdom
          <br />
          <br />
          <b>Service Provider</b>
          <br />
          means any natural or legal person who processes the data on behalf of
          the Company. It refers to third-party companies or individuals
          employed by the Company to facilitate the Service, to provide the
          Service on behalf of the Company, to perform services related to the
          Service or to assist the Company in analyzing how the Service is used.
          <br />
          <br />
          <b>Third-party Social Media Service</b> <br />
          refers to any website or any social network website through which a
          User can log in or create an account to use the Service.
          <br />
          <br />
          <b>Personal Data</b>
          <br />
          is any information that relates to an identified or identifiable
          individual.
          <br />
          <br />
          <b>Cookies</b>
          <br />
          are small files that are placed on Your computer, mobile device or any
          other device by a website, containing the details of Your browsing
          history on that website among its many uses.
          <br />
          <br />
          <b>Device</b>
          <br />
          means any device that can access the Service such as a computer, a
          cellphone or a digital tablet.
          <br />
          <br />
          <b>Usage Data</b> <br />
          refers to data collected automatically, either generated by the use of
          the Service or from the Service infrastructure itself (for example,
          the duration of a page visit).
          <br />
          <br />
          <b>Collecting and Using Your Personal Data</b> <br />
          Types of Data Collected
          <br />
          Usage Data
          <br />
          Usage Data is collected automatically when using the Service.
          <br />
          <br />
          <br />
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
          <br />
          <br />
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
          <br />
          <br />
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
          <br />
          <br />
          <b>Tracking Technologies and Cookies</b>
          <br />
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service.
          <br />
          <br />
          You can instruct Your browser to refuse all Cookies or to indicate
          when a Cookie is being sent. However, if You do not accept Cookies,
          You may not be able to use some parts of our Service.
          <br />
          <br />
          Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
          remain on your personal computer or mobile device when You go offline,
          while Session Cookies are deleted as soon as You close your web
          browser. Learn more about cookies here: Cookies: What Do They Do?
          <br />
          <br />
          We use both session and persistent Cookies for the purposes set out
          below:
          <br />
          <br />
          <b>Necessary / Essential Cookies</b>
          <br />
          <br />
          Type: Session Cookies
          <br />
          <br />
          Administered by: Us
          <br />
          <br />
          Purpose: These Cookies are essential to provide You with services
          available through the Website and to enable You to use some of its
          features. They help to authenticate users and prevent fraudulent use
          of user accounts. Without these Cookies, the services that You have
          asked for cannot be provided, and We only use these Cookies to provide
          You with those services.
          <br />
          <br />
          Cookies Policy / Notice Acceptance Cookies
          <br />
          <br />
          Type: Persistent Cookies
          <br />
          <br />
          Administered by: Us
          <br />
          <br />
          Purpose: These Cookies identify if users have accepted the use of
          cookies on the Website.
          <br />
          <br />
          <b>Functionality Cookies</b>
          <br />
          <br />
          Type: Persistent Cookies
          <br />
          <br />
          Administered by: Us
          <br />
          <br />
          Purpose: These Cookies allow us to remember choices You make when You
          use the Website, such as remembering your login details or language
          preference. The purpose of these Cookies is to provide You with a more
          personal experience and to avoid You having to re-enter your
          preferences every time You use the Website.
          <br />
          <br />
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy.
          <br />
          <br />
          <b>Google Analytics</b>
          <br />
          This website uses Google Analytics, a web analytics service provided
          by Google, Inc. (Google). Google Analytics uses "cookies", which are
          text files placed on your computer, to help the website analyze how
          users use the site. The information generated by the cookie about your
          use of the website (including your IP address) will be transmitted to
          and stored by Google on servers in the United States. In case of
          activation of the IP anonymization, Google will truncate/anonymize the
          last octet of the IP address for Member States of the European Union
          as well as for other parties to the Agreement on the European Economic
          Area. Only in exceptional cases, the full IP address is sent to and
          shortened by Google servers in the USA. On behalf of the website
          provider, Google will use this information for the purpose of
          evaluating your use of the website, compiling reports on website
          activity for website operators and providing other services relating
          to website activity and internet usage to the website provider. Google
          will not associate your IP address with any other data held by Google.
          You may refuse the use of cookies by selecting the appropriate
          settings on your browser. However, please note that if you do this,
          you may not be able to use the full functionality of this website.
          Furthermore, you can prevent Google's collection and use of data
          (cookies and IP address) by downloading and installing the browser
          plug-in available under https://tools.google.com/dlpage/gaoptout.
          <br />
          <br />
          <b>Use of Your Personal Data</b>
          <br />
          This Company does not collect Personal Data for any purposes.
          <br />
          <br />
          <b>Children's Privacy</b>
          <br />
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please Contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
          <br />
          <br />
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent's consent before We collect and use that
          information.
          <br />
          <br />
          <b>Links to Other Websites</b>
          <br />
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party's site. We strongly advise You to review the Privacy
          Policy of every site You visit.
          <br />
          <br />
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
          <br />
          <br />
          <b>Changes to this Privacy Policy</b> <br />
          We may update our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
          <br />
          <br />
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the "Last
          Updated" date at the top of this Privacy Policy.
          <br />
          <br />
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
          <br />
          <br />
          <b>Contact Us</b>
          <br />
          If you have any questions about this Privacy Policy, You can contact
          us:
          <br />
          <br />
          <b>By email: info@solid.fish</b>
        </p>
      </div>
      <Footer />
    </section>
  );
};

export default PrivacyPolicy;
